project_id = "cbbqyxxwpkfouvmmjton"

[functions.create-payment-authorization]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.verify-password]
verify_jwt = false

[functions.dispatch-intervention]
verify_jwt = false

[functions.check-dispatch-timeouts]
verify_jwt = false

[functions.notify-quote-modification]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.cancel-payment]
verify_jwt = false

[functions.notify-status-change]
verify_jwt = false

[functions.increment-authorization]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.calculate-partner-statistics]
verify_jwt = false

[functions.payment-authorization-status]
verify_jwt = false

[functions.notify-payment-required]
verify_jwt = false

[functions.notify-technician-dispatch]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.insert-work-photos]
verify_jwt = false

[functions.send-cancellation-invoice]
verify_jwt = false

[functions.send-welcome-admin-email]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.send-technician-arrival-reminder]
verify_jwt = false

[functions.schedule-arrival-reminders]
verify_jwt = false
