project_id = "cbbqyxxwpkfouvmmjton"

[functions.create-payment-authorization]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.verify-password]
verify_jwt = false

[functions.dispatch-intervention]
verify_jwt = false

[functions.check-dispatch-timeouts]
verify_jwt = false

[functions.notify-quote-modification]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.cancel-payment]
verify_jwt = false

[functions.notify-status-change]
verify_jwt = false
